### ISSUE TITLE
Deceiving library reliability

### ISSUE THREAD

**Issue by thefabulousdev** [screendriver/cp-cli#1]
The module has a build status badge on green deceiving the public about the reliability of the package. 
The only existing test :

```js
describe('cp-cli', () => {
  it('should do anything', () => {
    expect(true).to.be.true();
  });
```

**Comment by screendriver** [comment]
Yes that's true. I know that because I have written this one. This has some reasons:

1. this tool is excatly one day old. I needed that tool immediately for a private project and I had no time to write a useful test.
1. when you look at my code the only thing that I call is [yargs](https://www.npmjs.com/package/yargs) and [fs-extra](https://www.npmjs.com/package/fs-extra). So the only thing to test would be to test that these both libraries are working as expected. It is only a simple wrapper around fs-extra#copy().
1. I don't have any idea how to test the argumenst that `yargs` is reading because `yargs` read these from the command line.

So if you have any idea how to write a unit test for that any pull request would be welcome.

**Comment by thefabulousdev** [comment]
I was going to make the exact same library, hence I found this one. 
For the `fs-extra`, I do not know chai but we should use spies to check that the correct method was called with the correct arguments. For yargs, I'll investigate.

**Comment by thefabulousdev** [comment]
Sharing the knowledge: https://jstesting.jcoglan.com/cli.pdf

**Comment by screendriver** [comment]
Thank you for sharing the link 👍 

But as I said: **at the moment** there is no meaningfulness to write tests. The only thing we would test is that `yargs` and `fs-extra` are working as expected 😉 You shouldn't write unit tests that only test external libraries.

**Comment by thefabulousdev** [comment]
No.. we would test that the cli application indeed uses the first argument as `source` and the second one as `target` and that `fse.copy` is called with these arguments in the correct order. 

If this seems too trivial to you then why not remove the build passing badge? It should be trivial for users too right?

**Comment by screendriver** [comment]
I removed `cp-cli-test.js` for you. This file should originally be a skeleton for future unit tests.

The build passing badge remains because a "build" consists of two steps:

1. Code linting
1. Unit testing

I will add the one unit test that you wishes later when I have more time for that.

**Comment by thefabulousdev** [comment]
I'll write it, today, as soon as I'm off work.

**Comment by screendriver** [comment]
Fixed with ff36430c8c3e2ee7eea16779c81ff32f06ced356

**Comment by thefabulousdev** [comment]
Awesome.

**Comment by screendriver** [comment]
Hmm strange. Local at my machine the tests are running, on Travis they aren't :flushed:

**Comment by screendriver** [comment]
Fixed 😎 My bad
